### Категориальный - категориальный

In [43]:
import pandas as pd
from feature_metrics import calculate_statistics_cat_cat
import numpy as np

data = {
    'num_feature1': [1.2, 2.4, 1.8, 3.2, 2.4],
    'num_feature2': [0.1, 0.2, 0.3, 0.4, 0.5],
    'random_feature': np.random.rand(5),
    'feature1': ['A', 'B', 'A', 'C', 'B'],
    'feature2': ['X', 'Y', 'X', 'Z', 'Y'],
    'target':   ['No', 'No', 'Yes', 'Yes', 'Yes']
}
df = pd.DataFrame(data)

# Расчет метрик относительно target
result = calculate_statistics_cat_cat(
    df, 
    target='target',
    features=None,
    p_values_only=False,
    quantize_numeric=True,
    nan_policy="drop",
    n_bins=2
)

result

,v_cramer,v_cramer_p,adjusted_mutual_info,normalized_mutual_info,adjusted_rand_index
num_feature1,0.000000,1.000000,-0.098181,0.201964,-0.153846
num_feature2,0.250000,0.576150,0.251267,0.432538,0.166667
random_feature,0.000000,1.000000,-0.292300,0.020571,-0.250000
feature1,0.408248,0.659241,-0.423567,0.137151,-0.363636
feature2,0.408248,0.659241,-0.423567,0.137151,-0.363636

In [35]:
import numpy as np
import pandas as pd

data = {
    'num_feature1': [1.2, 2.4, 1.8, 3.2, 2.4],
    'num_feature2': [0.1, 0.2, 0.3, 0.4, 0.5],
    'random_feature': np.random.rand(5),
    'feature1': ['A', 'B', 'A', 'C', 'B'],
    'feature2': ['X', 'Y', 'X', 'Z', 'Y'],
    'target':   ['Yes', 'No', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)

# Расчет метрик между всеми признаками
result = calculate_statistics_cat_cat(
    df, 
    target=None,
    features=None,
    p_values_only=False,
    quantize_numeric=True,
    nan_policy="drop",
    n_bins=10
)

result['adjusted_mutual_info']

,num_feature1,num_feature2,random_feature,feature1,feature2,target
num_feature1,1.0,-0.0,-0.0,0.615385,0.615385,-0.223623
num_feature2,-0.0,1.0,1.0,-0.0,-0.0,-0.0
random_feature,-0.0,1.0,1.0,-0.0,-0.0,-0.0
feature1,0.615385,-0.0,-0.0,1.0,1.0,0.105892
feature2,0.615385,-0.0,-0.0,1.0,1.0,0.105892
target,-0.223623,-0.0,-0.0,0.105892,0.105892,1.0

### Категориальный - числовой

In [11]:
from feature_metrics import calculate_statistics_cat_num
import pandas as pd
import numpy as np

data = {
    'num_feature1': [1.2, 2.4, 1.8, 3.2, 2.4],
    'num_feature2': [0.1, 0.2, 0.3, 0.4, 0.5],
    'random_feature': np.random.rand(5),
    'cat_feature': ['A', 'A', 'B', 'B', 'B'],
    'target':      ['Yes', 'No', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)

# Расчет метрик относительно target
result = calculate_statistics_cat_num(
    df,
    # target='cat_feature',
    target=None,
    features=None,
    p_values_only=False,
    nan_policy="drop",
    averaging="micro"
)

result['roc_auc']

               cat_feature    target
num_feature1           0.1 -0.166667
num_feature2           0.2       0.0
random_feature    0.133333  0.066667

### Числовой - числовой

In [31]:
from feature_metrics import calculate_statistics_num_num
import pandas as pd
import numpy as np

data = {
    'num_feature1': [1.2, 2.4, 1.8, 3.2, 2.4],
    'num_feature2': [0.1, 0.2, 0.3, 0.4, 0.5],
    'random_feature': np.random.rand(5),
    'cat_feature': ['A', 'A', 'B', 'B', 'B'],
    'target':      ['Yes', 'No', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)

# Расчет метрик относительно target
result = calculate_statistics_num_num(
    df,
    target=None,
    features=None,
    p_values_only=False,
    nan_policy="drop",
)

result['spearman_r2']

               num_feature1 num_feature2 random_feature
num_feature1            1.0     0.444737       0.010526
num_feature2       0.444737          1.0           0.01
random_feature     0.010526         0.01            1.0